feat(matpat): add logging

diff --git a/bin/matpat b/bin/matpat
--- a/bin/matpat
+++ b/bin/matpat
@@ -34,6 +34,9 @@ set -o errexit
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 # SOFTWARE.
 
+OS_COPY_CMD="${OS_COPY_CMD:-os-cb}"
+OS_OPEN_CMD="${OS_OPEN_CMD:-os-open}"
+
 find_shutils_dir() {
     __util_src="$0"
     while [ -h "$__util_src" ]; do
@@ -48,8 +51,27 @@ find_shutils_dir() {
 }
 
 SHUTILS_DIR=${SHUTILS_DIR:-$(find_shutils_dir)}
-OS_COPY_CMD="${OS_COPY_CMD:-os-cb}"
-OS_OPEN_CMD="${OS_OPEN_CMD:-os-open}"
+
+if [ -z "$MATPAT_LOGS" ]; then
+    if [ -d "$XDG_STATE_HOME" ]; then
+        MATPAT_LOGS="$XDG_STATE_HOME/shutils/matpat.log"
+    elif [ -d "$HOME/.local/state" ]; then
+        MATPAT_LOGS="$HOME/.local/state/shutils/matpat.log"
+    else
+        MATPAT_LOGS="${SHUTILS_DIR}/logs/matpat.log"
+    fi
+    echo "$MATPAT_LOGS"
+    mkdir -p "$(dirname "$MATPAT_LOGS")"
+elif [ "$MATPAT_LOGS" = "0" ]; then
+    MATPAT_LOGS="/dev/null"
+else
+    echo "$MATPAT_LOGS"
+    mkdir -p "$(dirname "$MATPAT_LOGS")"
+fi
+
+logger() {
+    echo "$(date +%Y-%m-%dT%H:%M:%S 2>>"$MATPAT_LOGS") > $1" >>"$MATPAT_LOGS"
+}
 
 # --------------------------------------------------------------------- }}}
 # Usage info                                                            {{{
@@ -73,17 +95,14 @@ uri() {
     _uri_misc_schemes='s3://|rediss?://|git://|svn://|cvs://|nfs://|file://|data:)'
     _uri_schemes="(?:$_uri_network_schemes|$_uri_app_schemes|$_uri_misc_schemes)"
     grep -oP "${_uri_schemes}[a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*(\([a-zA-Z0-9\-\@;\/?:&=%\$_.+!*\x27,~#]*\)|[a-zA-Z0-9\-\@;\/?:&=%\$_+*~])+"
-
 }
 
 ip_address() {
     grep -oP '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
-
 }
 
 git_sha() {
     grep -oE '\b[0-9a-f]{5,40}\b'
-
 }
 
 git_sha_range() {
@@ -91,7 +110,7 @@ git_sha_range() {
 }
 
 # --------------------------------------------------------------------- }}}
-# Find and select or print matches                                      {{{
+# Find/select or print matches                                          {{{
 # --------------------------------------------------------------------- {|}
 
 select_match() {
@@ -114,24 +133,29 @@ select_pattern() {
 
 match_pattern() {
     if [ -z "$1" ]; then
+        logger "ERROR: no pattern specified or selected"
         help "No pattern specified."
     fi
-    if [ -n "$_tmux_mode" ]; then
-        _matches=$(for pane in $(tmux list-pane -a -F "#S:#I.#P"); do
+    if [ -n "$tmux_mode" ]; then
+        logger "finding matches in all open tmux panes"
+        matches=$(for pane in $(tmux list-pane -a -F "#S:#I.#P"); do
             tmux capture-pane -t "$pane" -p
         done | $1)
     else
+        logger "finding matches from stdin"
         # shellcheck disable=2086
-        _matches=$(eval $1)
+        matches=$(eval $1)
     fi
 
-    if [ -n "$_select_mode" ]; then
-        select_match "$_matches"
+    if [ -n "$select_mode" ]; then
+        logger "interactively selecting a match"
+        select_match "$matches"
     else
-        echo "$_matches"
+        logger "printing matches to stdout"
+        echo "$matches"
     fi
 
-    unset _select_mode _tmux_mode _matches
+    unset select_mode tmux_mode matches
 }
 
 # --------------------------------------------------------------------- }}}
@@ -144,33 +168,54 @@ stdin_is_pipe_like() { [ -p /dev/stdin ] || ! [ -t 0 ]; }
 main() {
     # Print usage info if `matpat` is called with no args, unless stdin
     # is piped, in which case prompt the user to select a pattern.
-    ! stdin_is_pipe_like && [ -z "$1" ] && help
-    _pattern="select"
+    if ! stdin_is_pipe_like; then
+        [ -z "$1" ] && help
+        # Automatically turn on tmux mode if attached and stdin is
+        # not piped, otherwise it hangs waiting for stdin.
+        [ -n "$TMUX" ] && tmux_mode=1
+    fi
 
-    # Automatically turn on tmux mode if attached and stdin is
-    # not piped, otherwise it hangs waiting for stdin.
-    ! stdin_is_pipe_like && [ -n "$TMUX" ] && _tmux_mode=1
+    pattern="select"
 
     while getopts p:ths opt; do
         case $opt in
             h) help ;;
-            p) _pattern="$OPTARG" ;;
-            t) _tmux_mode=1 ;;
-            s) _select_mode=1 ;;
-            *) help "Invalid flag: $opt" ;;
+            p)
+                logger "pattern specified: $pattern"
+                pattern="$OPTARG"
+                ;;
+            t)
+                logger "tmux mode enabled"
+                tmux_mode=1
+                ;;
+            s)
+                logger "select mode enabled"
+                select_mode=1
+                ;;
+            *)
+                logger "ERROR: Invalid flag \"$opt\""
+                help "Invalid flag: $opt"
+                ;;
         esac
     done
 
     shift "$((OPTIND - 1))"
 
-    case $_pattern in
+    case $pattern in
         i | ip | ip_address) match_pattern ip_address ;;
         r | range | git_range) match_pattern git_sha_range ;;
         s | sha | git_sha) match_pattern git_sha ;;
         u | uri | url) match_pattern uri ;;
-        select) match_pattern "$(select_pattern)" ;;
-        *) help "Unknown pattern: $_pattern" ;;
+        select)
+            logger "no pattern specified, interactively selecting one"
+            match_pattern "$(select_pattern)"
+            ;;
+        *)
+            logger "ERROR: Unknown pattern \"$pattern\""
+            help "Unknown pattern: $pattern"
+            ;;
     esac
 }
 
+echo "" >>"$MATPAT_LOGS"
 main "$@"
